from tkinter import *

root = Tk()
root.title("Maze Breaker")

left_frame = Frame(root)
right_frame = Frame(root)
left_frame.pack(side=LEFT)
right_frame.pack(side=RIGHT)


def one_step():
    print("one step")


def start():
    print("start")


def pause():
    print("pause")


button_one_step = Button(right_frame, text="One Step", fg="blue", command=one_step)
button_start = Button(right_frame, text="Start", fg="blue", command=start)
button_pause = Button(right_frame, text="Pause", fg="blue", command=pause)

photo_cloud = PhotoImage(file="image/cloud.png")
photo_d = PhotoImage(file="image/d.png")
photo_dl = PhotoImage(file="image/dl.png")
photo_dlr = PhotoImage(file="image/dlr.png")
photo_dr = PhotoImage(file="image/dr.png")
photo_l = PhotoImage(file="image/l.png")
photo_lr = PhotoImage(file="image/lr.png")
photo_r = PhotoImage(file="image/r.png")
photo_u = PhotoImage(file="image/u.png")
photo_ud = PhotoImage(file="image/ud.png")
photo_udl = PhotoImage(file="image/udl.png")
photo_udlr = PhotoImage(file="image/udlr.png")
photo_udr = PhotoImage(file="image/udr.png")
photo_ul = PhotoImage(file="image/ul.png")
photo_ulr = PhotoImage(file="image/ulr.png")
photo_ur = PhotoImage(file="image/ur.png")

labels = [[0 for x in range(5)] for y in range(5)]
labels[0][0] = Label(left_frame, image=photo_cloud, width=50, height=50)
labels[0][0].grid(row=0, column=0)
labels[0][1] = Label(left_frame, image=photo_d, width=50, height=50)
labels[0][1].grid(row=0, column=1)
labels[0][2] = Label(left_frame, image=photo_cloud, width=50, height=50)
labels[0][2].grid(row=0, column=2)
labels[0][3] = Label(left_frame, image=photo_cloud, width=50, height=50)
labels[0][3].grid(row=0, column=3)
labels[0][4] = Label(left_frame, image=photo_d, width=50, height=50)
labels[0][4].grid(row=0, column=4)
labels[1][0] = Label(left_frame, image=photo_r, width=50, height=50)
labels[1][0].grid(row=1, column=0)
labels[1][1] = Label(left_frame, image=photo_udlr, width=50, height=50)
labels[1][1].grid(row=1, column=1)
labels[1][2] = Label(left_frame, image=photo_lr, width=50, height=50)
labels[1][2].grid(row=1, column=2)
labels[1][3] = Label(left_frame, image=photo_dlr, width=50, height=50)
labels[1][3].grid(row=1, column=3)
labels[1][4] = Label(left_frame, image=photo_ul, width=50, height=50)
labels[1][4].grid(row=1, column=4)
labels[2][0] = Label(left_frame, image=photo_cloud, width=50, height=50)
labels[2][0].grid(row=2, column=0)
labels[2][1] = Label(left_frame, image=photo_ud, width=50, height=50)
labels[2][1].grid(row=2, column=1)
labels[2][2] = Label(left_frame, image=photo_cloud, width=50, height=50)
labels[2][2].grid(row=2, column=2)
labels[2][3] = Label(left_frame, image=photo_ud, width=50, height=50)
labels[2][3].grid(row=2, column=3)
labels[2][4] = Label(left_frame, image=photo_cloud, width=50, height=50)
labels[2][4].grid(row=2, column=4)
labels[3][0] = Label(left_frame, image=photo_cloud, width=50, height=50)
labels[3][0].grid(row=3, column=0)
labels[3][1] = Label(left_frame, image=photo_ur, width=50, height=50)
labels[3][1].grid(row=3, column=1)
labels[3][2] = Label(left_frame, image=photo_lr, width=50, height=50)
labels[3][2].grid(row=3, column=2)
labels[3][3] = Label(left_frame, image=photo_udl, width=50, height=50)
labels[3][3].grid(row=3, column=3)
labels[3][4] = Label(left_frame, image=photo_cloud, width=50, height=50)
labels[3][4].grid(row=3, column=4)
labels[4][0] = Label(left_frame, image=photo_cloud, width=50, height=50)
labels[4][0].grid(row=4, column=0)
labels[4][1] = Label(left_frame, image=photo_cloud, width=50, height=50)
labels[4][1].grid(row=4, column=1)
labels[4][2] = Label(left_frame, image=photo_cloud, width=50, height=50)
labels[4][2].grid(row=4, column=2)
labels[4][3] = Label(left_frame, image=photo_u, width=50, height=50)
labels[4][3].grid(row=4, column=3)
labels[4][4] = Label(left_frame, image=photo_cloud, width=50, height=50)
labels[4][4].grid(row=4, column=4)

button_one_step.pack(fill=X)
button_start.pack(fill=X)
button_pause.pack(fill=X)
root.mainloop()
